#!/bin/bash

 gfortran -c bisec.for
 gfortran -c chisqsiz.for
 gfortran -c erfc.for
 gfortran -c erf.for
 gfortran -c fisherest.for
 gfortran -c fishersi.for
 gfortran -c fishsizb.for
 gfortran -c g.for
 gfortran -c invttail.for
 gfortran -c ppower.for
 gfortran -c iprelris.for
 gfortran -c ipsize.for
 gfortran -c ldeltasi.for
 gfortran -c lpower.for
 gfortran -c lsamples.for
 gfortran -c mhor.for
 gfortran -c mhpowerfcn.for
 gfortran -c mhsize.for
 gfortran -c moddsrat.for
 gfortran -c mpower.for
 gfortran -c msamples.for
 gfortran -c pfunc1.for
 gfortran -c phi.for
 gfortran -c pone.for
 gfortran -c powfcn.for
 gfortran -c ppower.for
 gfortran -c prelrisk.for
 gfortran -c psize.for
 gfortran -c r1.for
 gfortran -c r2.for
 gfortran -c r3.for
 gfortran -c ssize.for
 gfortran -c survfunc.for
 gfortran -c survpowe.for
 gfortran -c survrelh.for
 gfortran -c survsize.for
 gfortran -c tcrvalue.for
 gfortran -c tcumfcn.for
 gfortran -c tcum.for
 gfortran -c tdeltasi.for
 gfortran -c tpower.for
 gfortran -c tsamples.for
 gfortran -c tsize.for
 gfortran -c tuppow.for
 gfortran -c zcrvalue.for
 gfortran -c zero.for
