	REAL FUNCTION PFUNC1(P1)
	IMPLICIT NONE
C
C    Arguments
C
	REAL P1
C
C    Functions
C
	REAL ZCRVALUE
C
C    Locals
C
	REAL Q1,Q0,P10,P01,PA,QA,XALPHA,XBETA
C
C    Common from main
C
	REAL ALPHA,BETA,N,P0,PHI_V,ZALPHA,ZBETA
	COMMON/PCOM/ALPHA,BETA,N,P0,PHI_V,ZALPHA,ZBETA
C
C Code:
C
	XALPHA=ALPHA
	XBETA=BETA

	ZALPHA=ZCRVALUE(XALPHA/2.)
	ZBETA=ZCRVALUE(XBETA)
	Q1=1.-P1
	Q0=1.-P0
	P10=P1*Q0 - PHI_V*SQRT(P1*Q1*P0*Q0)
	P01=Q1*P0 - PHI_V*SQRT(P1*Q1*P0*Q0)
	PA=P10/(P01+P10)
	QA=1.-PA
	PFUNC1=((ZALPHA*0.5+ZBETA*SQRT(PA*QA))**2 / 
     .		((PA-0.5)**2 * (P01+P10)))-N
C
C    Done.
C
	RETURN
	END