	REAL FUNCTION SURVFUNC1(M2)
C
C  Functions
	IMPLICIT NONE
C
	REAL ZCRVALUE
C
C    Arguments
C
	REAL M2
C
C    Data passed in common to functions.
C
	REAL ALPHA,BETA,M1,A,F,N,M,ZALPHA,ZBETA
	COMMON /SURVCOM1/ ALPHA,BETA,M1,A,F,N,M
	COMMON /SURVCOM2/ ZALPHA, ZBETA
C
C    Locals
C
	REAL PA,GF,P,R,MM
C
C Code:
C
	MM=(M1+M2)/2.
	PA=(1.-EXP(-LOG(2.)*A/MM))/(LOG(2.)*A/MM)
	GF=EXP(-LOG(2.)*F/MM)
	P=1.-PA*GF
	ZALPHA=ZCRVALUE(ALPHA/2.)
	ZBETA=ZCRVALUE(BETA)
	R=M2/M1
	SURVFUNC1= ( (ZALPHA+ZBETA)**2 * ((1.+1./M)/P)/(LOG(R))**2 )-N
	RETURN
	END